% runs G3P3 model step-by-step to test interupted simulation methodology
% that will be used to encorperate the matlab storage model

clear, clc, close all
import OMMatlab.*
omc = OMMatlab();

%% load G3P3 Modelica Model
omc.ModelicaSystem("OMMatlab_FallingParticleReceiverSystem-REV4.mo", ...
    "FallingParticleReceiverSystem.Models.G3P3_System", ["Modelica", "Complex", ...
    "ModelicaServices", "ModelicaReference"]);

%% load parameter database
params = readtable('G3P3_Parameters.xlsx');
initialConditions = readtable('G3P3_ICs.xlsx');
dynamicParams = params(strcmp(params.Type, 'dynamic'), :);
dynamicNames = strings(1, length(dynamicParams.Name));
icNames = strings(1, length(initialConditions.Name));
icReplacementNames = icNames;
initNames = {'DecompTime.hour_day', ...
             'DecompTime.day_number', 'IntermediateStorage.m_s'};
for i = 1:length(dynamicNames)
    dynamicNames(i) = dynamicParams.Name(i); 
end
for i = 1:length(icNames)
   icNames(i) = initialConditions.Name(i);
   icReplacementNames(i) = initialConditions.ReplacedWith(i);
end

% check avaliable model parameters
% omc.getParameters()

%% load modified storage bin outlet temperature profile
Tout_mod_table = readtable('G3P3_Modified_Tout.xlsx', 'Sheet', 'Tout');
Tout_mod = Tout_mod_table.Tout_mod;
Tout = Tout_mod_table.Tout;

m_dot_out_table = readtable('G3P3_Modified_Tout.xlsx', 'Sheet', 'm_dot');
m_dot_out = m_dot_out_table.m_dot;

mass_table = readtable('G3P3_Modified_Tout.xlsx', 'Sheet', 'm');
mass = mass_table.m;

%% run single simulation step
% omc.setSimulationOptions(["stopTime=60", "stepSize=60", ...
%                           "solver=dassl", "tolerance=1e-08"]);
% omc.simulate("G3P3_results.mat");

%% extract end states for dynamic variables
% results = omc.getSolutions(dynamicNames);
% newParams = strings(1, length(results));
% for i = 1:length(newParams)
%     newParams(i) = strcat(dynamicNames(i), '=', string(results{i}(end))); 
% end
% omc.setParameters(newParams);

%% get new initial condition values
% results = omc.getSolutions(icReplacementNames);
% newICs = strings(1, length(results));
% for i = 1:length(newICs)
%     newICs(i) = strcat(icNames(i), '=', string(results{i}(end))); 
% end
% omc.setParameters(newICs);

%% run next step
% omc.setSimulationOptions(["stopTime=60", "stepSize=60", ...
%                           "solver=dassl", "tolerance=1e-08"]);
% omc.simulate("G3P3_results.mat");

%% encorperate procedure to run a full simulation
endTime = 3600*24*3;          % (s) end time for full simulation
timeStep = 60;                % (s) time step for discrete simulations
% omc.setSimulationOptions([strcat("stopTime=", string(timeStep)), ...
%                           strcat("stepSize=", string(timeStep)), ...
%                           "solver=dassl", "tolerance=1e-08"]);
N = ceil(endTime/timeStep);
DNI0 = 1e-10; HX_m_dot0 = 1e-10; Heater_m_dot0 = 0.1; 
intStorage_m_dot_s_out0 = 0.0; RecieverPID_y_start = 10;
% x = table(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'VariableNames', {'time', 'hotBin_T_s_out', ...
%                          'hotBin_m_s', 'hotBin_m_dot_s_out', 'hotBin_m_dot_s_in', ...
%                          'intStorage_m_s', 'intStorage_m_dot_s_out', 'intStorage_m_dot_s_in', ...
%                          'DNI', 'ReceiverPID_y', 'weatherDNI', 'hour'});
% Junction_params = table(0, 0, 0, 0, 0, 0, 0, 'VariableNames', ...
%                         {'hour', ...
%                          'hotBinDischarge_m_dot_s_in', ...
%                          'hotBinDischarge_m_dot_s_out', ...
%                          'heaterDischarge_m_dot_s_in', ...
%                          'heaterDischarge_m_dot_s_out', ...
%                          'hotBinBypass_m_dot_s_in', ...
%                          'hotBinBypass_m_dot_s_out'});
FreeFallDucts = table(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                      0, 0, 0, 'VariableNames', {'hour', ...
                               'ColdBinDischarge_m_dot', ...
                               'ColdBinDischarge_Tout', ...
                               'HeatExchangerDownComer_m_dot', ...
                               'HeatExchangerDownComer_Tout', ...
                               'HotBinBypass_m_dot', ...
                               'HotBinBypass_Tout', ...
                               'IntermediateStorageDownComer_m_dot', ...
                               'IntermediateStorageDownComer_Tout', ...
                               'ColdBinBypass_m_dot', ...
                               'ColdBinBypass_Tout', ...
                               'BucketElevatorDownComer_m_dot', ...
                               'BucketElevatorDownComer_Tout', ...
                               'HotBinDischarge_m_dot', ...
                               'HotBinDischarge_Tout', ...
                               'ReceiverDownComer_m_dot', ...
                               'ReceiverDownComer_Tout', ...
                               'ReceiverBypass_m_dot', ...
                               'ReceiverBypass_Tout'});



HX_params = table(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'VariableNames', ...
                                                {'hour', ...
                                                'DNI', ...
                                                'Qheater', ...
                                                'm_dot_CO2_in', ...
                                                'm_dot_CO2_out', ...
                                                'm_dot_s_in', ...
                                                'm_dot_s_out', ...
                                                'hCO2_1', ...
                                                'hCO2_2', ...
                                                'hCO2_3', ...
                                                'hCO2_4', ...
                                                'hCO2_5', ...
                                                'hCO2_6', ...
                                                'hCO2_7', ...
                                                'hCO2_8', ...
                                                'hCO2_9', ...
                                                'hCO2_10', ...
                                                'hCO2_11', ...
                                                'hCO2_12', ...
                                                'hCO2_13', ...
                                                'hCO2_14', ...
                                                'hCO2_15', ...
                                                'hCO2_16', ...
                                                'hCO2_17', ...
                                                'hCO2_18', ...
                                                'hCO2_19', ...
                                                'hCO2_20', ...
                                                'hs_1', ...
                                                'hs_2', ...
                                                'hs_3', ...
                                                'hs_4', ...
                                                'hs_5', ...
                                                'hs_6', ...
                                                'hs_7', ...
                                                'hs_8', ...
                                                'hs_9', ...
                                                'hs_10', ...
                                                'hs_11', ...
                                                'hs_12', ...
                                                'hs_13', ...
                                                'hs_14', ...
                                                'hs_15', ...
                                                'hs_16', ...
                                                'hs_17', ...
                                                'hs_18', ...
                                                'hs_19', ...
                                                'hs_20', ...
                                                'TCO2_1', ...
                                                'TCO2_2', ...
                                                'TCO2_3', ...
                                                'TCO2_4', ...
                                                'TCO2_5', ...
                                                'TCO2_6', ...
                                                'TCO2_7', ...
                                                'TCO2_8', ...
                                                'TCO2_9', ...
                                                'TCO2_10', ...
                                                'TCO2_11', ...
                                                'TCO2_12', ...
                                                'TCO2_13', ...
                                                'TCO2_14', ...
                                                'TCO2_15', ...
                                                'TCO2_16', ...
                                                'TCO2_17', ...
                                                'TCO2_18', ...
                                                'TCO2_19', ...
                                                'TCO2_20', ...
                                                'Ts_1', ...
                                                'Ts_2', ...
                                                'Ts_3', ...
                                                'Ts_4', ...
                                                'Ts_5', ...
                                                'Ts_6', ...
                                                'Ts_7', ...
                                                'Ts_8', ...
                                                'Ts_9', ...
                                                'Ts_10', ...
                                                'Ts_11', ...
                                                'Ts_12', ...
                                                'Ts_13', ...
                                                'Ts_14', ...
                                                'Ts_15', ...
                                                'Ts_16', ...
                                                'Ts_17', ...
                                                'Ts_18', ...
                                                'Ts_19', ...
                                                'Ts_20'});
icResults = table(0, 0, 0, 0, 'VariableNames', {'hotBin_T_s_0', 'hotBin_m_s_0', 'coldBin_T_s_0', 'coldBin_m_s_0'});
for k = 1:N
    omc.setInputs([strcat("startTime=", string((k-1)*timeStep)), ...
                   strcat("k=", string(k)), ...
                   strcat("h=", string(timeStep)), ...
                   strcat("DNI0=", string(DNI0)), ...
                   strcat("HX_m_dot0=", string(HX_m_dot0)), ...
                   strcat("Heater_m_dot0=", string(Heater_m_dot0)), ...
                   strcat("intStorage_m_dot_s_out0=", ...
                   string(intStorage_m_dot_s_out0)), ...
                   strcat("hotBin_Tout=", string(Tout(k))), ...
                   strcat("hotBin_m_dot_out=", string(m_dot_out(k))), ...
                   strcat("hotBin_m_s=", string(mass(k)))]);
    omc.setSimulationOptions([strcat("startTime=", string((k-1)*timeStep)), ... 
                          strcat("stopTime=", string(k*timeStep)), ...
                          strcat("stepSize=", string(timeStep)), ...
                          "solver=dassl", "tolerance=1e-08"]);
    omc.getInputs()
    omc.simulate("G3P3_results.mat");
    % set new initial condition values
    results = omc.getSolutions(icReplacementNames);    
    newICs = strings(1, length(results));
    for i = 1:length(newICs)
        newICs(i) = strcat(icNames(i), '=', string(results{i}(end)));
    end
    omc.setParameters(newICs);
    % set new initialization inputs
    newInit = omc.getSolutions(initNames);
    intStorage_m_s = newInit{3}(end);
    hour_day = newInit{1}(end); day_number = newInit{2}(end);
    % heat exchanger operation 
    if mass(k) > 10000, HX_m_dot0 = 5.0; 
    elseif mass(k) < 1000, HX_m_dot0 = 1e-10; end
    % reciever operation
    if hour_day > 10 && hour_day <= 16
        if day_number >= 5 && day_number < 6
            DNI0 = 1e-10;
        elseif day_number >= 3 && day_number < 4
            DNI0 = 900;
        elseif day_number >= 7 && day_number < 8
            DNI0 = 850;
        else
            DNI0 = 1000;
        end
    else
        DNI0 = 1e-10;
    end
    % intermediate storage bin discharge control
    if intStorage_m_s > 10, intStorage_m_dot_s_out0 = 1;
    elseif intStorage_m_s < 1, intStorage_m_dot_out0 = 0;
    end
    % store results
%     x_ = omc.getSolutions(["time", "IntermediateStorage.m_s", ...
%                            "IntermediateStorage.m_dot_s_out", "IntermediateStorage.m_dot_s_in", "DNI", ...
%                            "ReceiverPID.y", "Weather.DNI", "DecompTime.hour"]);                      
%                      
%     Junction_params_ = omc.getSolutions(["DecompTime.hour", ...
%                                          "HotBinDischarge.m_dot_s_in", ...
%                                          "HotBinDischarge.m_dot_s_out", ...
%                                          "HeaterDischarge.m_dot_s_in", ...
%                                          "HeaterDischarge.m_dot_s_out", ...
%                                          "HotBinBypass.m_dot_s_in", ...
%                                          "HotBinBypass.m_dot_s_out"]);

    FreeFallDucts_ = omc.getSolutions(["DecompTime.hour", ...
                   'ColdBinDischarge.ParticleOutlet.m_dot', ...
                   'ColdBinDischarge.ParticleOutlet.T', ...
                   'HeatExchangerDownComer.ParticleOutlet.m_dot', ...
                   'HeatExchangerDownComer.ParticleOutlet.T', ...
                   'HotBinBypass.ParticleOutlet.m_dot', ...
                   'HotBinBypass.ParticleOutlet.T', ...
                   'IntermediateStorageDownComer.ParticleOutlet.m_dot', ...
                   'IntermediateStorageDownComer.ParticleOutlet.T', ...
                   'ColdBinBypass.ParticleOutlet.m_dot', ...
                   'ColdBinBypass.ParticleOutlet.T', ...
                   'BucketElevatorDownComer.ParticleOutlet.m_dot', ...
                   'BucketElevatorDownComer.ParticleOutlet.T', ...
                   'HotBinDischarge.ParticleOutlet.m_dot', ...
                   'HotBinDischarge.ParticleOutlet.T', ...
                   'ReceiverDownComer.ParticleOutlet.m_dot', ...
                   'ReceiverDownComer.ParticleOutlet.T', ...
                   'ReceiverBypass.ParticleOutlet.m_dot', ...
                   'ReceiverBypass.ParticleOutlet.T']);
    
                       
    HX_params_ = omc.getSolutions(["DecompTime.hour", ...
                                   "DNI", ...
                                   "ParticleHeater.Q_in", ...
                                   "ParticleHeatExchanger.m_dot_CO2_in", ...
                                   "ParticleHeatExchanger.m_dot_CO2_out", ...
                                   "ParticleHeatExchanger.m_dot_s_in", ...
                                   "ParticleHeatExchanger.m_dot_s_out", ...
                                   "ParticleHeatExchanger.h_CO2[1]", ...
                                   "ParticleHeatExchanger.h_CO2[2]", ...
                                   "ParticleHeatExchanger.h_CO2[3]", ...
                                   "ParticleHeatExchanger.h_CO2[4]", ...
                                   "ParticleHeatExchanger.h_CO2[5]", ...
                                   "ParticleHeatExchanger.h_CO2[6]", ...
                                   "ParticleHeatExchanger.h_CO2[7]", ...
                                   "ParticleHeatExchanger.h_CO2[8]", ...
                                   "ParticleHeatExchanger.h_CO2[9]", ...
                                   "ParticleHeatExchanger.h_CO2[10]", ...
                                   "ParticleHeatExchanger.h_CO2[11]", ...
                                   "ParticleHeatExchanger.h_CO2[12]", ...
                                   "ParticleHeatExchanger.h_CO2[13]", ...
                                   "ParticleHeatExchanger.h_CO2[14]", ...
                                   "ParticleHeatExchanger.h_CO2[15]", ...
                                   "ParticleHeatExchanger.h_CO2[16]", ...
                                   "ParticleHeatExchanger.h_CO2[17]", ...
                                   "ParticleHeatExchanger.h_CO2[18]", ...
                                   "ParticleHeatExchanger.h_CO2[19]", ...
                                   "ParticleHeatExchanger.h_CO2[20]", ...
                                   "ParticleHeatExchanger.h_s[1]", ...
                                   "ParticleHeatExchanger.h_s[2]", ...
                                   "ParticleHeatExchanger.h_s[3]", ...
                                   "ParticleHeatExchanger.h_s[4]", ...
                                   "ParticleHeatExchanger.h_s[5]", ...
                                   "ParticleHeatExchanger.h_s[6]", ...
                                   "ParticleHeatExchanger.h_s[7]", ...
                                   "ParticleHeatExchanger.h_s[8]", ...
                                   "ParticleHeatExchanger.h_s[9]", ...
                                   "ParticleHeatExchanger.h_s[10]", ...
                                   "ParticleHeatExchanger.h_s[11]", ...
                                   "ParticleHeatExchanger.h_s[12]", ...
                                   "ParticleHeatExchanger.h_s[13]", ...
                                   "ParticleHeatExchanger.h_s[14]", ...
                                   "ParticleHeatExchanger.h_s[15]", ...
                                   "ParticleHeatExchanger.h_s[16]", ...
                                   "ParticleHeatExchanger.h_s[17]", ...
                                   "ParticleHeatExchanger.h_s[18]", ...
                                   "ParticleHeatExchanger.h_s[19]", ...
                                   "ParticleHeatExchanger.h_s[20]", ...
                                   "ParticleHeatExchanger.T_CO2[1]", ...
                                   "ParticleHeatExchanger.T_CO2[2]", ...
                                   "ParticleHeatExchanger.T_CO2[3]", ...
                                   "ParticleHeatExchanger.T_CO2[4]", ...
                                   "ParticleHeatExchanger.T_CO2[5]", ...
                                   "ParticleHeatExchanger.T_CO2[6]", ...
                                   "ParticleHeatExchanger.T_CO2[7]", ...
                                   "ParticleHeatExchanger.T_CO2[8]", ...
                                   "ParticleHeatExchanger.T_CO2[9]", ...
                                   "ParticleHeatExchanger.T_CO2[10]", ...
                                   "ParticleHeatExchanger.T_CO2[11]", ...
                                   "ParticleHeatExchanger.T_CO2[12]", ...
                                   "ParticleHeatExchanger.T_CO2[13]", ...
                                   "ParticleHeatExchanger.T_CO2[14]", ...
                                   "ParticleHeatExchanger.T_CO2[15]", ...
                                   "ParticleHeatExchanger.T_CO2[16]", ...
                                   "ParticleHeatExchanger.T_CO2[17]", ...
                                   "ParticleHeatExchanger.T_CO2[18]", ...
                                   "ParticleHeatExchanger.T_CO2[19]", ...
                                   "ParticleHeatExchanger.T_CO2[20]", ...
                                   "ParticleHeatExchanger.T_s[1]", ...
                                   "ParticleHeatExchanger.T_s[2]", ...
                                   "ParticleHeatExchanger.T_s[3]", ...
                                   "ParticleHeatExchanger.T_s[4]", ...
                                   "ParticleHeatExchanger.T_s[5]", ...
                                   "ParticleHeatExchanger.T_s[6]", ...
                                   "ParticleHeatExchanger.T_s[7]", ...
                                   "ParticleHeatExchanger.T_s[8]", ...
                                   "ParticleHeatExchanger.T_s[9]", ...
                                   "ParticleHeatExchanger.T_s[10]", ...
                                   "ParticleHeatExchanger.T_s[11]", ...
                                   "ParticleHeatExchanger.T_s[12]", ...
                                   "ParticleHeatExchanger.T_s[13]", ...
                                   "ParticleHeatExchanger.T_s[14]", ...
                                   "ParticleHeatExchanger.T_s[15]", ...
                                   "ParticleHeatExchanger.T_s[16]", ...
                                   "ParticleHeatExchanger.T_s[17]", ...
                                   "ParticleHeatExchanger.T_s[18]", ...
                                   "ParticleHeatExchanger.T_s[19]", ...
                                   "ParticleHeatExchanger.T_s[20]"]);                                   
%     icResults_ = omc.getSolutions(["HotBin.T_s_0", "HotBin.m_s_0", ...
%                            "ColdBin.T_s_0", "IntermediateStorage.m_s_0"]);
%     x = [x; {x_{1}(end), x_{2}(end), x_{3}(end), x_{4}(end), ...
%              x_{5}(end), x_{6}(end), x_{7}(end), x_{8}(end), ...
%              x_{9}(end), x_{10}(end), x_{11}(end), x_{12}(end)}];
%     Junction_params = [Junction_params; {Junction_params_{1}(end), ...
%                                          Junction_params_{2}(end), ...
%                                          Junction_params_{3}(end), ...
%                                          Junction_params_{4}(end), ...
%                                          Junction_params_{5}(end), ...
%                                          Junction_params_{6}(end), ...
%                                          Junction_params_{7}(end)}];

    FreeFallDucts = [FreeFallDucts; {FreeFallDucts_{1}(end), ...
                                     FreeFallDucts_{2}(end), ...
                                     FreeFallDucts_{3}(end), ...
                                     FreeFallDucts_{4}(end), ...
                                     FreeFallDucts_{5}(end), ...
                                     FreeFallDucts_{6}(end), ...
                                     FreeFallDucts_{7}(end), ...
                                     FreeFallDucts_{8}(end), ...
                                     FreeFallDucts_{9}(end), ...
                                     FreeFallDucts_{10}(end), ...
                                     FreeFallDucts_{11}(end), ...
                                     FreeFallDucts_{12}(end), ...
                                     FreeFallDucts_{13}(end), ...
                                     FreeFallDucts_{14}(end), ...
                                     FreeFallDucts_{15}(end), ...
                                     FreeFallDucts_{16}(end), ...
                                     FreeFallDucts_{17}(end), ...
                                     FreeFallDucts_{18}(end), ...
                                     FreeFallDucts_{19}(end)}];

    HX_params = [HX_params; {HX_params_{1}(end), ...
                             HX_params_{2}(end), ...
                             HX_params_{3}(end), ...
                             HX_params_{4}(end), ...
                             HX_params_{5}(end), ...
                             HX_params_{6}(end), ...
                             HX_params_{7}(end), ...
                             HX_params_{8}(end), ...
                             HX_params_{9}(end), ...
                             HX_params_{10}(end), ...
                             HX_params_{11}(end), ...
                             HX_params_{12}(end), ...
                             HX_params_{13}(end), ...
                             HX_params_{14}(end), ...
                             HX_params_{15}(end), ...
                             HX_params_{16}(end), ...
                             HX_params_{17}(end), ...
                             HX_params_{18}(end), ...
                             HX_params_{19}(end), ...
                             HX_params_{20}(end), ...
                             HX_params_{21}(end), ...
                             HX_params_{22}(end), ...
                             HX_params_{23}(end), ...
                             HX_params_{24}(end), ...
                             HX_params_{25}(end), ...
                             HX_params_{26}(end), ...
                             HX_params_{27}(end), ...
                             HX_params_{28}(end), ...
                             HX_params_{29}(end), ...
                             HX_params_{30}(end), ...
                             HX_params_{31}(end), ...
                             HX_params_{32}(end), ...
                             HX_params_{33}(end), ...
                             HX_params_{34}(end), ...
                             HX_params_{35}(end), ...
                             HX_params_{36}(end), ...
                             HX_params_{37}(end), ...
                             HX_params_{38}(end), ...
                             HX_params_{39}(end), ...
                             HX_params_{40}(end), ...
                             HX_params_{41}(end), ...
                             HX_params_{42}(end), ...
                             HX_params_{43}(end), ...
                             HX_params_{44}(end), ...
                             HX_params_{45}(end), ...
                             HX_params_{46}(end), ...
                             HX_params_{47}(end), ...
                             HX_params_{48}(end), ...
                             HX_params_{49}(end), ...
                             HX_params_{50}(end), ...
                             HX_params_{51}(end), ...
                             HX_params_{52}(end), ...
                             HX_params_{53}(end), ...
                             HX_params_{54}(end), ...
                             HX_params_{55}(end), ...
                             HX_params_{56}(end), ...
                             HX_params_{57}(end), ...
                             HX_params_{58}(end), ...
                             HX_params_{59}(end), ...
                             HX_params_{60}(end), ...
                             HX_params_{61}(end), ...
                             HX_params_{62}(end), ...
                             HX_params_{63}(end), ...
                             HX_params_{64}(end), ...
                             HX_params_{65}(end), ...
                             HX_params_{66}(end), ...
                             HX_params_{67}(end), ...
                             HX_params_{68}(end), ...
                             HX_params_{69}(end), ...
                             HX_params_{70}(end), ...
                             HX_params_{71}(end), ...
                             HX_params_{72}(end), ...
                             HX_params_{73}(end), ...
                             HX_params_{74}(end), ...
                             HX_params_{75}(end), ...
                             HX_params_{76}(end), ...
                             HX_params_{77}(end), ...
                             HX_params_{78}(end), ...
                             HX_params_{79}(end), ...
                             HX_params_{80}(end), ...
                             HX_params_{81}(end), ...
                             HX_params_{82}(end), ...
                             HX_params_{83}(end), ...
                             HX_params_{84}(end), ...
                             HX_params_{85}(end), ...
                             HX_params_{86}(end), ...
                             HX_params_{87}(end)}];                                                                                      
%     icResults = [icResults; {icResults_{1}(end), icResults_{2}(end), icResults_{3}(end), icResults_{4}(end)}];
end








